INSERT INTO ADDRESS(ID, CITY, STATE, COUNTRY, ZIPCODE)
  VALUES(-1, 'Fairfield', 'Iowa', 'US', '52556');

INSERT INTO PROJECT(ID, STATUS, DESCRIPTION, START_DATE, END_DATE, ADDRESS_ID)
  VALUES(-1, 'STARTED', 'This is a project description', '2018-01-01', '2018-04-01', -1);

INSERT INTO PROJECT(ID, STATUS, DESCRIPTION, START_DATE, END_DATE, ADDRESS_ID)
  VALUES(-2, 'STARTED', 'This is a project description 2', '2018-08-01', '2018-10-01', -1);

INSERT INTO PROJECT(ID, STATUS, DESCRIPTION, START_DATE, END_DATE)
  VALUES(-3, 'FINISHED', 'This is a project description 3', '2018-10-01', '2018-12-01');

INSERT INTO TASK(ID, DESCRIPTION, STATUS, START_DATE, END_DATE, PROJECT_ID)
  VALUES(-1, 'Task 1', 'STARTED', sysdate, sysdate, -1);
INSERT INTO TASK(ID, DESCRIPTION, STATUS, START_DATE, END_DATE, PROJECT_ID)
  VALUES(-2, 'Task 2', 'STARTED', sysdate, sysdate, -1);
INSERT INTO TASK(ID, DESCRIPTION, STATUS, START_DATE, END_DATE, PROJECT_ID)
  VALUES(-3, 'Task 3', 'STARTED', sysdate, sysdate, -2);

INSERT INTO TASK_RESOURCE(ID, RESOURCE_TYPE, TASK_ID, REQUIRED_RESOURCES)
  VALUES(-1, 'DEVELOPER', -1, 2);
INSERT INTO TASK_RESOURCE(ID, RESOURCE_TYPE, TASK_ID, REQUIRED_RESOURCES)
  VALUES(-2, 'DEVOPS', -1, 2);
INSERT INTO TASK_RESOURCE(ID, RESOURCE_TYPE, TASK_ID, REQUIRED_RESOURCES)
  VALUES(-3, 'DEVOPS', -2, 2);



INSERT INTO VOLUNTEER(ID, NAME) VALUES (-1, 'Volunteer 1');
INSERT INTO VOLUNTEER(ID, NAME) VALUES (-2, 'Volunteer 2');
INSERT INTO VOLUNTEER_SKILLS(VOLUNTEER_ID, SKILLS) VALUES (-1, 'DEVELOPER');
INSERT INTO VOLUNTEER_SKILLS(VOLUNTEER_ID, SKILLS) VALUES (-1, 'BA');

INSERT INTO VOLUNTEER_SKILLS(VOLUNTEER_ID, SKILLS) VALUES (-2, 'BA');

INSERT INTO PROJECT_VOLUNTEER(PROJECT_ID, VOLUNTEER_ID) VALUES (-1, -1);